name: ci

on:
  pull_request:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - run: make cosmocc
      - run: make libxml2 libxslt
      - run: make xmlcatalog.com xmllint.com xsltproc.com

      - name: Upload xmlcatalog.com
        uses: actions/upload-artifact@v4
        with:
          name: xmlcatalog.com
          path: xmlcatalog.com
          compression-level: 0
      - name: Upload xmllint.com
        uses: actions/upload-artifact@v4
        with:
          name: xmllint.com
          path: xmllint.com
          compression-level: 0
      - name: Upload xsltproc.com
        uses: actions/upload-artifact@v4
        with:
          name: xsltproc.com
          path: xsltproc.com
          compression-level: 0
